name: check_lib

on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Check Lib Lint
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
